//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int Bid { get; set; }
        public int Fid { get; set; }
        public string PhoneNo { get; set; }
        public string Branch { get; set; }
        public string ContactPerson { get; set; }
        public bool IsFixed { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> MatureDate { get; set; }
        public Nullable<int> InterestRuleId { get; set; }
        public Nullable<decimal> MinimumBalance { get; set; }
        public string AccountNo { get; set; }
        public Nullable<bool> ForLiquidity { get; set; }
        public int BranchId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual FinAcc FinAcc { get; set; }
        public virtual FinAcc FinAcc1 { get; set; }
        public virtual InterestRule InterestRule { get; set; }
    }
}
