//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrnchGlobal
    {
        public int BrnchID { get; set; }
        public byte CalSID { get; set; }
        public byte CalCID { get; set; }
        public System.DateTime Tdate { get; set; }
        public bool UseLimit { get; set; }
        public Nullable<int> fisYear { get; set; }
        public Nullable<decimal> VnoExt { get; set; }
        public Nullable<bool> atclosing { get; set; }
        public Nullable<System.DateTime> MigTdate { get; set; }
        public string CleCode { get; set; }
        public Nullable<byte> intExpMod { get; set; }
        public Nullable<decimal> Floint { get; set; }
        public Nullable<bool> IsCalcIOnI { get; set; }
    }
}
