//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionDefination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimensionDefination()
        {
            this.DimensionValues = new HashSet<DimensionValue>();
        }
    
        public int DDId { get; set; }
        public string DefName { get; set; }
        public Nullable<byte> IsManual { get; set; }
        public Nullable<int> TId { get; set; }
    
        public virtual DimensionTable DimensionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimensionValue> DimensionValues { get; set; }
    }
}
