//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinAcc()
        {
            this.BankInfoes = new HashSet<BankInfo>();
            this.BankInfoes1 = new HashSet<BankInfo>();
            this.DimensionVSLedgers = new HashSet<DimensionVSLedger>();
            this.RemittanceCustomers = new HashSet<RemittanceCustomer>();
            this.SchmDetails = new HashSet<SchmDetail>();
            this.SubsiTitle_not_used = new HashSet<SubsiTitle_not_used>();
            this.SubsiVSFIds = new HashSet<SubsiVSFId>();
            this.Voucher2 = new HashSet<Voucher2>();
            this.Voucher21 = new HashSet<Voucher2>();
            this.Voucher2T = new HashSet<Voucher2T>();
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int Fid { get; set; }
        public string Fname { get; set; }
        public Nullable<int> Pid { get; set; }
        public int F2Type { get; set; }
        public byte[] Content { get; set; }
        public Nullable<bool> DebitRestriction { get; set; }
        public Nullable<bool> CreditRestriction { get; set; }
        public string Code { get; set; }
        public string Alias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankInfo> BankInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankInfo> BankInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimensionVSLedger> DimensionVSLedgers { get; set; }
        public virtual FinSys2 FinSys2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemittanceCustomer> RemittanceCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchmDetail> SchmDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsiTitle_not_used> SubsiTitle_not_used { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsiVSFId> SubsiVSFIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher2> Voucher2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher2> Voucher21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher2T> Voucher2T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
