//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidaysInYear
    {
        public int HolidayId { get; set; }
        public int YearId { get; set; }
        public int MonthId { get; set; }
        public int Holiday { get; set; }
        public string Description { get; set; }
    }
}
