//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTemplate
    {
        public int MenuTemplateId { get; set; }
        public string MTName { get; set; }
        public int DesignationId { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
    }
}
