//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubsiSetup()
        {
            this.SubsiVSFIds = new HashSet<SubsiVSFId>();
        }
    
        public int SSId { get; set; }
        public int STBId { get; set; }
        public string Title { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> CurrentNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsiVSFId> SubsiVSFIds { get; set; }
    }
}
