//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiTitle_not_used
    {
        public int STid { get; set; }
        public int FId { get; set; }
        public string STitleName { get; set; }
        public string STPrefix { get; set; }
        public int Slength { get; set; }
        public int CurrentNo { get; set; }
    
        public virtual FinAcc FinAcc { get; set; }
    }
}
