//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiDetail
    {
        public int SDID { get; set; }
        public int CId { get; set; }
        public int FId { get; set; }
        public string AccNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<decimal> DebitLimit { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public int BranchId { get; set; }
    }
}
