//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiVSOpeningBalance
    {
        public int Id { get; set; }
        public int FId { get; set; }
        public int SubsiId { get; set; }
        public Nullable<int> FYID { get; set; }
        public decimal OpeningBal { get; set; }
        public Nullable<decimal> ClosingBal { get; set; }
    }
}
