//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiTable
    {
        public int STBId { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> NeedMap { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
