//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempFinAcc
    {
        public short FID { get; set; }
        public string aname { get; set; }
        public Nullable<short> apid { get; set; }
        public byte acode { get; set; }
        public Nullable<byte> FSide { get; set; }
    }
}
