//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVsRole
    {
        public int URId { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> EffFrom { get; set; }
        public Nullable<System.DateTime> EffTo { get; set; }
        public bool Status { get; set; }
    }
}
