//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher2()
        {
            this.Voucher3 = new HashSet<Voucher3>();
            this.Voucher5 = new HashSet<Voucher5>();
            this.Voucher4 = new HashSet<Voucher4>();
        }
    
        public int V2Id { get; set; }
        public Nullable<int> Fid { get; set; }
        public Nullable<int> V1id { get; set; }
        public string Particulars { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher3> Voucher3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher5> Voucher5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher4> Voucher4 { get; set; }
        public virtual FinAcc FinAcc { get; set; }
        public virtual FinAcc FinAcc1 { get; set; }
        public virtual Voucher1 Voucher1 { get; set; }
        public virtual Voucher1 Voucher11 { get; set; }
    }
}
