//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher3T
    {
        public int V3TId { get; set; }
        public int V2TId { get; set; }
        public int SId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Voucher2T Voucher2T { get; set; }
    }
}
