//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher1T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher1T()
        {
            this.Voucher2T = new HashSet<Voucher2T>();
        }
    
        public int V1TId { get; set; }
        public int VNo { get; set; }
        public System.DateTime TDate { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public int CTId { get; set; }
        public int VNId { get; set; }
        public string Narration { get; set; }
        public System.DateTime VerifiedOn { get; set; }
    
        public virtual CurrencyType CurrencyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher2T> Voucher2T { get; set; }
    }
}
