//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherBal
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> FId { get; set; }
        public Nullable<int> FYId { get; set; }
        public Nullable<decimal> OPBal { get; set; }
        public Nullable<decimal> CLBal { get; set; }
    }
}
