//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherCount
    {
        public int VCountID { get; set; }
        public int VTypeID { get; set; }
        public short FYID { get; set; }
        public int VCount { get; set; }
    
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
