//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessRole
    {
        public int AccId { get; set; }
        public int RoleId { get; set; }
        public int MenuId { get; set; }
    
        public virtual LoginRole LoginRole { get; set; }
        public virtual MenuList MenuList { get; set; }
    }
}
