//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContext : DbContext
    {
        public DbContext()
            : base("name=DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDef> AddressDefs { get; set; }
        public virtual DbSet<AddressDetail> AddressDetails { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyGrp> CompanyGrps { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactDef> ContactDefs { get; set; }
        public virtual DbSet<ContactPrsn> ContactPrsns { get; set; }
        public virtual DbSet<CustAll> CustAlls { get; set; }
        public virtual DbSet<Individual> Individuals { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<AccessRole> AccessRoles { get; set; }
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<BatchCount> BatchCounts { get; set; }
        public virtual DbSet<BatchDescription> BatchDescriptions { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Company1> Company1 { get; set; }
        public virtual DbSet<CurrencyType> CurrencyTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DimensionDefination> DimensionDefinations { get; set; }
        public virtual DbSet<DimensionValue> DimensionValues { get; set; }
        public virtual DbSet<DimensionVSLedger> DimensionVSLedgers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<FinAcc> FinAccs { get; set; }
        public virtual DbSet<FinSys1> FinSys1 { get; set; }
        public virtual DbSet<FinSys2> FinSys2 { get; set; }
        public virtual DbSet<FiscalYear> FiscalYears { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<InterestMinimumBalance> InterestMinimumBalances { get; set; }
        public virtual DbSet<InterestRule> InterestRules { get; set; }
        public virtual DbSet<InterestTime> InterestTimes { get; set; }
        public virtual DbSet<LoginRole> LoginRoles { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuList> MenuLists { get; set; }
        public virtual DbSet<OnProccessingVoucher> OnProccessingVouchers { get; set; }
        public virtual DbSet<RegisterUser> RegisterUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SMTPConfig> SMTPConfigs { get; set; }
        public virtual DbSet<SubLedger> SubLedgers { get; set; }
        public virtual DbSet<SubsiTitle> SubsiTitles { get; set; }
        public virtual DbSet<SubsiVSFId> SubsiVSFIds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemInfo> SystemInfoes { get; set; }
        public virtual DbSet<UnverifiedCheque> UnverifiedCheques { get; set; }
        public virtual DbSet<UnverifiedVoucherDetail> UnverifiedVoucherDetails { get; set; }
        public virtual DbSet<UnverifiedVoucherMaster> UnverifiedVoucherMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VoucherCheque> VoucherCheques { get; set; }
        public virtual DbSet<VoucherCount> VoucherCounts { get; set; }
        public virtual DbSet<VoucherDetail> VoucherDetails { get; set; }
        public virtual DbSet<VoucherMaster> VoucherMasters { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
    }
}
