//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        public int ADetId { get; set; }
        public int CustId { get; set; }
        public int ADId { get; set; }
        public string Zone { get; set; }
        public string District { get; set; }
        public string City_Village { get; set; }
        public string Ward { get; set; }
        public string Tole { get; set; }
        public string HouseNo_ { get; set; }
    
        public virtual AddressDef AddressDef { get; set; }
        public virtual Info Info { get; set; }
    }
}
