//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchCount
    {
        public int BCountId { get; set; }
        public int BId { get; set; }
        public int BCount { get; set; }
        public short FYID { get; set; }
        public int VTypeId { get; set; }
    
        public virtual BatchDescription BatchDescription { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
