//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CustComId { get; set; }
        public int CustId { get; set; }
        public int CTId { get; set; }
        public int CGId { get; set; }
        public int CNId { get; set; }
        public string RegNo { get; set; }
        public string ContPerson { get; set; }
        public string ContPerDesignation { get; set; }
        public string ParentId { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual CompanyGrp CompanyGrp { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual Info Info { get; set; }
    }
}
