//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int CntctId { get; set; }
        public int CustId { get; set; }
        public int CDId { get; set; }
        public string ContactNo { get; set; }
        public string SerialNo { get; set; }
    
        public virtual ContactDef ContactDef { get; set; }
        public virtual Info Info { get; set; }
    }
}
