//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPrsn
    {
        public int CPId { get; set; }
        public int CustId { get; set; }
        public string CntPsnName { get; set; }
        public string Designation { get; set; }
        public string CntNo { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
