//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        public int CustIndividualId { get; set; }
        public int CustomerId { get; set; }
        public int OccupationId { get; set; }
        public int CGId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
    
        public virtual CompanyGrp CompanyGrp { get; set; }
        public virtual Info Info { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
