//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnProccessingVoucher
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TempId { get; set; }
        public Nullable<int> Fid { get; set; }
        public string Particulars { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public Nullable<int> SLId { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public string Payee { get; set; }
        public Nullable<int> TV2Id { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
