//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public int UserId { get; set; }
        public int EmpId { get; set; }
        public int RoleId { get; set; }
        public string UserName { get; set; }
        public string UPassword { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual LoginRole LoginRole { get; set; }
    }
}
