//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubLedger()
        {
            this.UnverifiedVoucherDetails = new HashSet<UnverifiedVoucherDetail>();
            this.VoucherDetails = new HashSet<VoucherDetail>();
        }
    
        public int SLId { get; set; }
        public int STId { get; set; }
        public int CId { get; set; }
        public string CodeNo { get; set; }
    
        public virtual CustAll CustAll { get; set; }
        public virtual SubsiTitle SubsiTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnverifiedVoucherDetail> UnverifiedVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherDetail> VoucherDetails { get; set; }
    }
}
