//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubsiTitle()
        {
            this.SubLedgers = new HashSet<SubLedger>();
            this.SubsiVSFIds = new HashSet<SubsiVSFId>();
        }
    
        public int STid { get; set; }
        public int Fid { get; set; }
        public string STitleName { get; set; }
        public string STPrefix { get; set; }
        public int Slength { get; set; }
        public int CurrentNo { get; set; }
    
        public virtual FinAcc FinAcc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubLedger> SubLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsiVSFId> SubsiVSFIds { get; set; }
    }
}
