//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsiVSFId
    {
        public int SFId { get; set; }
        public Nullable<int> STId { get; set; }
        public Nullable<int> Fid { get; set; }
    
        public virtual FinAcc FinAcc { get; set; }
        public virtual SubsiTitle SubsiTitle { get; set; }
    }
}
