//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInfo
    {
        public int Id { get; set; }
        public string SystemName { get; set; }
        public string Logo { get; set; }
        public string Discription { get; set; }
        public bool IsActive { get; set; }
        public string CompanyName { get; set; }
        public string CopyrightDiscription { get; set; }
        public bool State { get; set; }
    }
}
