//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnverifiedCheque
    {
        public int UnverifiedCqid { get; set; }
        public string ChequeNo { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public decimal ChequeAmount { get; set; }
        public string Payee { get; set; }
        public int TV2id { get; set; }
    
        public virtual UnverifiedVoucherDetail UnverifiedVoucherDetail { get; set; }
    }
}
