//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnverifiedVoucherDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnverifiedVoucherDetail()
        {
            this.UnverifiedCheques = new HashSet<UnverifiedCheque>();
        }
    
        public int TV2id { get; set; }
        public Nullable<int> Fid { get; set; }
        public string Particulars { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<int> TVid { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> SLId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual SubLedger SubLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnverifiedCheque> UnverifiedCheques { get; set; }
        public virtual UnverifiedVoucherMaster UnverifiedVoucherMaster { get; set; }
    }
}
