//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoucherMaster()
        {
            this.VoucherDetails = new HashSet<VoucherDetail>();
        }
    
        public int V1Id { get; set; }
        public int VoucherNo { get; set; }
        public Nullable<int> BId { get; set; }
        public System.DateTime VouDate { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime ApprovedOn { get; set; }
        public string PreparedBy { get; set; }
        public System.DateTime PreparedOn { get; set; }
        public short FYId { get; set; }
        public int CTId { get; set; }
        public int TotalTransaction { get; set; }
        public int VTypeID { get; set; }
        public string CompanyId { get; set; }
        public string Narration { get; set; }
    
        public virtual BatchDescription BatchDescription { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual FiscalYear FiscalYear1 { get; set; }
        public virtual FiscalYear FiscalYear2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherDetail> VoucherDetails { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
